name: Test for NCR
on:
  workflow_dispatch:
jobs:
  firstjob:
    runs-on: ubuntu-latest
    steps:
      - name: What is the runner IP address
        run: |
          curl ident.me
      - name: connectivity test to NCR
        run: |
          nc -vz 153.84.5.134 443

